
name: publish

on:
  release:
    types:
      - created
  workflow_dispatch:


jobs:
  publish:

    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-20.04, windows-2019, macos-11]
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.11.2
    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
    - name: Build a source tarball
      run: |
        pip install build
        python -m build --sdist --outdir dist/ .
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: ./wheelhouse/
